version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: chatbot_db
    environment:
      POSTGRES_DB: chatbot_feedback_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123abc!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build: .
    container_name: chatbot_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatbot_feedback_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123abc!
      WHATSAPP_MOCK: "true" 
    depends_on:
      - db

volumes:
  postgres_data: